name: make linux

on:
  push:
    branches: [ "master","Dev0ke" ]
  pull_request:
    branches: [ "master","Dev0ke" ]
  release:
    types: [created,published] # 表示在创建新的 Release 时触发
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.3' # The Go version to download (if necessary) and use.
        
    - name: gui
      run: cd gui/velociraptor/ && npm install
      
    - name: make gui
      run: cd gui/velociraptor/ && make build
      
    - name: go mod
      run : go mod tidy
      
    - name: make bin
      run: export PATH=/go/bin:$PATH && make linux
      
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: linux-bin
        path: output/velociraptor-v0.7.1-linux-amd64
